### ISSUE TITLE
this is not working any more?

### ISSUE THREAD

**Issue by jackpxyz** [wpkc/fail2ban-filter-ninjafirewall-logs#1]
Thanks for the step by step about this config but this is ignoring all the lines of the log

Running tests
=============

Use   failregex filter file : ninjafirewall-logs, basedir: /etc/fail2ban
Use      datepattern : {^LN-BEG} : Default Detectors
Use         log file : /var/www/html/tienda/wp-content/nfwlog/firewall_2023-02.php
Use         encoding : UTF-8

Results
=======

Failregex: 0 total

Ignoreregex: 0 total

Date template hits:
|- [# of hits] date format
|  [10] {^LN-BEG}Epoch
`-

Lines: 11 lines, 0 ignored, 0 matched, 11 missed
[processed in 0.01 sec]

|- Missed line(s):
|  <?php exit; ?>
|  [1675357548] [0.00669] [global-sol.org] [#6973294] [0] [6] [107.150.23.171] [200] [GET] [/wp-admin/plugins.php] [Sanitising user input] [hex:485454505f524546455245523a20687474703a2f2f676c6f62616c2d736f6c2e6f72672f77702d61646d696e2f706c7567696e2d696e7374616c6c2e7068703f733d6e696e6a6125323532306669726577616c6c267461623d73656172636826747970653d7465726d]
|  [1675368935] [0] [global-sol.org] [#3900111] [0] [6] [0.0.0.0] [403] [N/A] [-] [Database changes detected] [hex:61646d696e6973747261746f72206163636f756e74]
|  [1675369080] [0] [global-sol.org] [#2333779] [0] [6] [107.150.23.171] [403] [GET] [/wp-admin/plugins.php] [Plugin deactivated by verlaine] [hex:4e616d653a206e67696e782d63616368652f6e67696e782d63616368652e706870]
|  [1675370599] [0.02698] [global-solutions.org] [#2699384] [0] [6] [107.150.23.171] [200] [POST] [/wp-login.php] [Sanitising user input] [hex:485454505f524546455245523a2068747470733a2f2f676c6f62616c2d736f6c7574696f6e732e6f72672f77702d6c6f67696e2e7068703f72656469726563745f746f3d6874747073253341253246253246676c6f62616c2d736f6c7574696f6e732e6f726725324677702d61646d696e253246267265617574683d31]
|  [1675370729] [0] [global-solutions.org] [#2431587] [0] [6] [107.150.23.171] [403] [POST] [/wp-login.php] [Logged in user] [hex:7665726c61696e65202861646d696e6973747261746f7229]
|  [1675372043] [0.00032] [global-solutions.org] [#6552711] [0] [1] [34.222.181.233] [404] [POST] [/wp-admin/admin-ajax.php] [Blocked access to admin-ajax.php] [hex:626f7420646574656374696f6e20697320656e61626c6564]
|  [1675379556] [0.00218] [global-solutions.org] [#2810986] [1] [3] [179.43.155.158] [404] [GET] [/wp-admin/admin-post.php] [Directory traversal #1] [hex:4745543a616c675f77635f7069665f646f776e6c6f61645f66696c65203d202e2e2f2e2e2f2e2e2f2e2e2f2e2e2f77702d636f6e6669672e706870]
|  [1675381469] [0.00026] [global-solutions.org] [#6253012] [0] [1] [46.166.171.186] [404] [GET] [/wp-login.php] [Blocked access to the login page] [hex:626f7420646574656374696f6e20697320656e61626c6564]
|  [1675382932] [0.00054] [global-solutions.org] [#6068663] [0] [1] [5.161.189.6] [404] [GET] [/wp-login.php] [Blocked access to the login page] [hex:626f7420646574656374696f6e20697320656e61626c6564]
|  [1675387080] [0.00042] [global-solutions.org] [#1498109] [0] [1] [52.167.144.39] [404] [GET] [/wp-admin/admin-ajax.php] [Blocked access to admin-ajax.php] [hex:626f7420646574656374696f6e20697320656e61626c6564]
`-

**Comment by wpkc** [comment]
Sorry about that, the regex for the domain name did not cover the "-" character.  I just uploaded a new version that should have more complete coverage for domain names.

**Comment by jackpxyz** [comment]
Thank you very much for the quick answer. It already detects the critical lines but doing the test it does not add the detected ip to the iptables.



Running tests
=============

Use   failregex filter file : ninjafirewall-logs, basedir: /etc/fail2ban
Use      datepattern : {^LN-BEG} : Default Detectors
Use         log file : /var/www/html/tienda/wp-content/nfwlog/firewall_2023-02.php
Use         encoding : UTF-8


Results
=======

Failregex: 15 total
|-  #) [# of hits] regular expression
|   1) [15] \[(?:[\d\.]{1,8})\] \[(?:[\w\.\-]{4,80})\] \[\#(?:\d{5,9})\] \[(?:\d{1,6})\] \[[12]\] \[<HOST>\] \[(?:\d{3})\] \[(?:POST|GET|PUT|PATCH|DELETE)\] \[
`-

Ignoreregex: 0 total

Date template hits:
|- [# of hits] date format
|  [133] {^LN-BEG}Epoch
`-

Lines: 134 lines, 0 ignored, 15 matched, 119 missed
[processed in 0.02 sec]

Missed line(s): too many to print.  Use --print-all-missed to print all 119 lines

**Comment by wpkc** [comment]
I'm not sure if fail2ban-regex will actually ban an IP, or just report matches.

My experience with this filter is that it very rarely bans anything, especially if you have maxretry set to 3 or higher.  And setting it lower is will ban too much.
